language: python
python:
    - "3.6"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
dist: bionic
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=./

install:
   - pip3 install -U platformio
   - platformio --version

script:
    - cd airrohr-firmware && pwd && ls -l && platformio run && ls -l builds/
    - cd ../airrohr-update-loader && pwd && ls -l && platformio run && ls -l builds/
